# .github/workflows/release.yaml

name: Release

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: go build -v -o bin/prometheus-nvidia-smi src/app.go
    - name: Test
      run: go test -v ./...
    - uses: wangyoucao577/go-release-action@v1.32
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: 1.18
        project_path: "./src"
        binary_name: "prometheus-nvidia-smi"
        extra_files: LICENSE README.md
